CREATE TABLE departement (
                             id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             nom             VARCHAR2(100)    NOT NULL UNIQUE,
                             description     CLOB,
                             responsable_id  NUMBER,
                             created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
                             updated_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON TABLE  departement                IS 'Départements de l entreprise';
COMMENT ON COLUMN departement.responsable_id IS 'Référence vers l employé responsable du département';

CREATE TABLE employe (
                         id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         keycloak_id     VARCHAR2(36)        NOT NULL UNIQUE,
                         matricule       VARCHAR2(20)         NOT NULL UNIQUE,
                         nom             VARCHAR2(100)        NOT NULL,
                         prenom          VARCHAR2(100)        NOT NULL,
                         email           VARCHAR2(150)        NOT NULL UNIQUE,
                         telephone       VARCHAR2(20),
                         date_naissance  DATE,
                         date_embauche   DATE                NOT NULL,
                         poste           VARCHAR2(100)        NOT NULL,
                         statut          VARCHAR2(20)        DEFAULT 'ACTIF' NOT NULL,
                         departement_id  NUMBER,
                         created_at      TIMESTAMP           DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         updated_at      TIMESTAMP           DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         CONSTRAINT chk_statut_employe CHECK (statut IN ('ACTIF', 'INACTIF', 'SUSPENDU')),
                         CONSTRAINT fk_employe_dept FOREIGN KEY (departement_id) REFERENCES departement(id) ON DELETE SET NULL
);

COMMENT ON TABLE  employe             IS 'Employés de l entreprise';
COMMENT ON COLUMN employe.keycloak_id IS 'UUID Keycloak';
COMMENT ON COLUMN employe.matricule   IS 'Matricule unique auto-généré';

ALTER TABLE departement
    ADD CONSTRAINT fk_dept_responsable
        FOREIGN KEY (responsable_id) REFERENCES employe(id) ON DELETE SET NULL;

CREATE TABLE contrat (
                         id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         employe_id      NUMBER          NOT NULL UNIQUE,
                         type            VARCHAR2(20)    NOT NULL,
                         date_debut      DATE            NOT NULL,
                         date_fin        DATE,
                         salaire_base    NUMBER(12, 2)   NOT NULL CHECK (salaire_base > 0),
                         created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         updated_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         CONSTRAINT fk_contrat_employe FOREIGN KEY (employe_id) REFERENCES employe(id) ON DELETE CASCADE,
                         CONSTRAINT chk_type_contrat CHECK (type IN ('CDI', 'CDD', 'STAGE', 'FREELANCE')),
                         CONSTRAINT chk_date_fin_required CHECK (
                             type = 'CDI' OR (type IN ('CDD', 'STAGE', 'FREELANCE') AND date_fin IS NOT NULL)
                             ),
                         CONSTRAINT chk_date_fin_apres_debut CHECK (date_fin IS NULL OR date_fin > date_debut)
);

CREATE TABLE conge (
                       id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       employe_id      NUMBER          NOT NULL,
                       approbateur_id  NUMBER,
                       type            VARCHAR2(20)    NOT NULL,
                       date_debut      DATE            NOT NULL,
                       date_fin        DATE            NOT NULL,
                       nombre_jours    NUMBER(3)       NOT NULL CHECK (nombre_jours > 0),
                       statut          VARCHAR2(20)    DEFAULT 'EN_ATTENTE' NOT NULL,
                       motif           CLOB,
                       created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
                       updated_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
                       CONSTRAINT fk_conge_employe FOREIGN KEY (employe_id) REFERENCES employe(id) ON DELETE CASCADE,
                       CONSTRAINT fk_conge_approbateur FOREIGN KEY (approbateur_id) REFERENCES employe(id) ON DELETE SET NULL,
                       CONSTRAINT chk_type_conge CHECK (type IN ('ANNUEL', 'MALADIE', 'MATERNITE', 'SANS_SOLDE')),
                       CONSTRAINT chk_statut_conge CHECK (statut IN ('EN_ATTENTE', 'APPROUVE', 'REJETE')),
                       CONSTRAINT chk_conge_dates CHECK (date_fin >= date_debut)
);

CREATE TABLE absence (
                         id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         employe_id  NUMBER      NOT NULL,
                         "DATE"      DATE        NOT NULL, -- "DATE" est un mot réservé dans Oracle
                         motif       CLOB,
                         justifiee   NUMBER(1)   DEFAULT 0 NOT NULL CHECK (justifiee IN (0,1)), -- Boolean simulé
                         created_at  TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         updated_at  TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         CONSTRAINT fk_absence_employe FOREIGN KEY (employe_id) REFERENCES employe(id) ON DELETE CASCADE,
                         CONSTRAINT uq_absence_employe_date UNIQUE (employe_id, "DATE")
);

CREATE TABLE fiche_de_paie (
                               id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               employe_id          NUMBER              NOT NULL,
                               mois                NUMBER(2)           NOT NULL CHECK (mois BETWEEN 1 AND 12),
                               annee               NUMBER(4)           NOT NULL CHECK (annee > 2000),
                               salaire_base        NUMBER(12, 2)      NOT NULL,
                               total_absences      NUMBER(3)           DEFAULT 0 NOT NULL CHECK (total_absences >= 0),
                               deduction_absences  NUMBER(12, 2)      DEFAULT 0 NOT NULL,
                               prime_presence      NUMBER(12, 2)      DEFAULT 0 NOT NULL,
                               cotisations_total   NUMBER(12, 2)      DEFAULT 0 NOT NULL,
                               salaire_net         NUMBER(12, 2)      NOT NULL,
                               statut              VARCHAR2(20)        DEFAULT 'BROUILLON' NOT NULL,
                               created_at          TIMESTAMP           DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               updated_at          TIMESTAMP           DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               CONSTRAINT fk_fiche_employe FOREIGN KEY (employe_id) REFERENCES employe(id),
                               CONSTRAINT chk_statut_paie CHECK (statut IN ('BROUILLON', 'VALIDEE', 'PAYEE')),
                               CONSTRAINT uq_fiche_paie_periode UNIQUE (employe_id, mois, annee),
                               CONSTRAINT chk_salaire_net_positif CHECK (salaire_net >= 0)
);


CREATE INDEX idx_emp_dept ON employe(departement_id);
CREATE INDEX idx_conge_emp ON conge(employe_id);
CREATE INDEX idx_fiche_emp ON fiche_de_paie(employe_id);


CREATE OR REPLACE TRIGGER trg_dept_upd
BEFORE UPDATE ON departement FOR EACH ROW
BEGIN :NEW.updated_at := CURRENT_TIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_emp_upd
BEFORE UPDATE ON employe FOR EACH ROW
BEGIN :NEW.updated_at := CURRENT_TIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_contrat_upd
BEFORE UPDATE ON contrat FOR EACH ROW
BEGIN :NEW.updated_at := CURRENT_TIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_conge_upd
BEFORE UPDATE ON conge FOR EACH ROW
BEGIN :NEW.updated_at := CURRENT_TIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_absence_upd
BEFORE UPDATE ON absence FOR EACH ROW
BEGIN :NEW.updated_at := CURRENT_TIMESTAMP; END;
/

CREATE OR REPLACE TRIGGER trg_paie_upd
BEFORE UPDATE ON fiche_de_paie FOR EACH ROW
BEGIN :NEW.updated_at := CURRENT_TIMESTAMP; END;
/